bgs/urls.py
from django.conf.urls import patterns, url
from bgs import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^view_project/(?P<project_id>.+)/$', views.view_project, name='view_project'),
    url(r'^edit_project/(?P<project_id>.+)/$', views.edit_project, name='edit_project'),
    url(r'^delete_project/(?P<project_id>.+)/$', views.delete_project, name='delete_project'),
    url(r'^download_project/(?P<project_id>.+)/$', views.download_project, name='download_project'),

    url( r'upload/', views.upload, name = 'jfu_upload' ),
    url( r'^delete/(?P<pk>\d+)$', views.upload_delete, name = 'jfu_delete' ),
    url(r'^view_uploaded_file/(?P<project_id>.+)/(?P<uploaded_file_id>\d+)$', views.view_uploaded_file, name='view_uploaded_file'),
    url(r'^poll_task_results/(?P<project_id>.+)/$', views.poll_task_results, name='poll_task_results'),
    url(r'^results/(?P<project_id>.+)/(?P<task_id>\d+)$', views.task_results, name='task_results'),
    url(r'^download_csv/(?P<project_id>.+)/(?P<csv_result_id>\d+)/$', views.download_csv, name='download_csv'),
    url(r'^styled_graph_editor/container/(?P<project_id>.+)/(?P<styled_graph_id>\d+)/(?P<hash_code>.+)/$', views.styled_graph_editor, name='styled_graph_editor'),

    url(r'^create_combo/(?P<project_id>.+)/$', views.create_combo, name='create_combo'),
    url(r'^view_combo/(?P<project_id>.+)/(?P<combo_id>\d+)/$', views.view_combo, name='view_combo'),
    url(r'^save_combo_columns/(?P<project_id>.+)/(?P<combo_id>\d+)/$', views.save_combo_columns, name='save_combo_columns'),
    url(r'^delete_combo/(?P<project_id>.+)/(?P<combo_id>\d+)/$', views.delete_combo, name='delete_combo'),

    url(r'^combo/columns/(?P<project_id>.+)/(?P<combo_id>\d+)/$', views.combo_columns, name='combo_columns'),
    url(r'^combo/graphs/(?P<project_id>.+)/(?P<combo_id>\d+)/$', views.combo_graphs, name='combo_graphs'),
    url(r'^combo/view_grid(?P<project_id>.+)/(?P<combo_id>\d+)/$', views.combo_grid, name='combo_grid'),
    
    url(r'^combo/grid/handler/(?P<project_id>.+)/(?P<combo_id>\d+)/$', views.combo_grid_handler, name='combo_grid_handler'),
    url(r'^combo/grid/cfg/(?P<project_id>.+)/(?P<combo_id>\d+)/$', views.combo_grid_config, name='combo_grid_config'),
    url(r'^combo/grid/download/(?P<project_id>.+)/(?P<combo_id>\d+)/$', views.download_combo_dataframe, name='download_combo_dataframe'),

    url(r'^view_auto_combo/(?P<project_id>.+)/(?P<result_type>.+)/$', views.view_auto_combo, name='view_auto_combo'),
    url(r'^combo/auto/grid/handler/(?P<project_id>.+)/(?P<result_type>.+)/$', views.auto_combo_grid_handler, name='auto_combo_grid_handler'),
    url(r'^combo/auto/grid/cfg/(?P<project_id>.+)/(?P<result_type>.+)/$', views.auto_combo_grid_config, name='auto_combo_grid_config'),
    url(r'^combo/auto/grid/download/(?P<project_id>.+)/(?P<result_type>.+)/$', views.download_auto_combo_dataframe, name='download_auto_combo_dataframe'),

    url(r'^styled_graph_editor/editor_tab/(?P<project_id>.+)/(?P<styled_graph_id>\d+)/$', views.graph_editor_tab, name='graph_editor_tab'),
    url(r'^category/category_tab/(?P<project_id>.+)/(?P<styled_graph_id>\d+)/$', views.graph_category_tab, name='graph_category_tab'),
    url(r'^category/create/(?P<project_id>.+)/(?P<styled_graph_id>\d+)/$', views.create_category, name='create_category'),
    url(r'^category/view/(?P<project_id>.+)/(?P<category_id>\d+)/$', views.view_category, name='view_category'),
    url(r'^category/delete/(?P<project_id>.+)/(?P<category_id>\d+)/$', views.delete_category, name='delete_category'),

    url(r'^category/samples_tab/(?P<project_id>.+)/(?P<styled_graph_id>\d+)/$', views.graph_samples_tab, name='graph_samples_tab'),
    url(r'^category/view_samples/(?P<project_id>.+)/(?P<category_id>\d+)/$', views.view_graph_samples, name='view_graph_samples'),
    
    url(r'^lost_projects$', views.lost_projects, name='lost_projects'),
    url(r'^docs/(?P<doc_name>.+)/$', views.docs, name='docs'),

)

bgs/models.py
from collections import OrderedDict
from django.db import models
from django.db.models.aggregates import Min
from django.db.models.deletion import SET_NULL
import grp
import hashlib
from model_utils.managers import InheritanceManager
from operator import attrgetter
import os
from smart_selects.db_fields import ChainedForeignKey
import stat

from bgs.models_enum import ComboType, CSVResultType, UploadedFileTypes, \
    GraphType
from bgs.plotly_json import plotly_data, plotly_layout
from bgs.utils.file_utils import mk_path, name_from_file_name
from bgs.utils.utils import Lazy
from biographserv import settings
import pandas as pd
from reference_server.reference.igenomes_reference import IGenomesReference


class Organism(models.Model):
    species_name = models.CharField(max_length=256)
    common_name = models.CharField(max_length=256)
    def __unicode__(self):
        return "%s (%s)" % (self.species_name, self.common_name)

class AnnotationGroup(models.Model):
    name = models.CharField(max_length=256)
    def __unicode__(self):
        return self.name

class Build(models.Model):
    organism = models.ForeignKey(Organism)
    annotation_group = models.ForeignKey(AnnotationGroup)
    name = models.CharField(max_length=256)

    def get_igenomes_reference(self):
        return IGenomesReference(self.organism.species_name, self.annotation_group.name, self.name)

    def __unicode__(self):
        return "%s/%s" % (self.annotation_group, self.name)

class Project(models.Model):
    MAX_EMAIL_LENGTH=256
    uuid = models.CharField(max_length=32, primary_key=True)
    organism = models.ForeignKey(Organism, null=True)
#    annotation_group = models.ForeignKey(AnnotationGroup, null=True)
    build = ChainedForeignKey(Build,
                              chained_field='organism',
                              chained_model_field='organism',
                              show_all=False,
                              auto_choose=True,
                              null=True)
    name = models.CharField(max_length=100)
    description = models.TextField()
    email = models.CharField(max_length=MAX_EMAIL_LENGTH)
    read_only = models.BooleanField(default=False)
    
    @property
    def date(self):
        # Earliest uploaded file
        return self.uploadedfile_set.all().aggregate(Min('date')).values()[0]

    def get_combos(self):
        combo_dicts = []
        for (combo_id, name) in self.combo_set.all().order_by("id").values_list("id", "name"):
            combo_data = {"id" : combo_id, "name" : name}
            combo_dicts.append(combo_data)
        return combo_dicts

    def create_default_genomic_ranges(self):
        GenomicRange.objects.create(project=self,
                                name='Promoter',
                                anchor=GenomicAnchor.TSS,
                                upstream=1000,
                                downstream=1000,
                                max_size=3000,
                                step_size=100,)

        GenomicRange.objects.create(project=self,
                                    name='Gene Body',
                                    anchor=GenomicAnchor.GENE_START_END,
                                    upstream=0,
                                    downstream=0,
                                    max_size=20000,
                                    step_size=500,)


    def __unicode__(self):
        name = self.name or self.pk
        if self.build:
            name = "%s (%s)" % (name, self.build)
        return name


class Combo(models.Model):
    project = models.ForeignKey(Project)
    name = models.CharField(max_length=100)
    combo_type = models.CharField(max_length=1, choices=ComboType.COMBO_TYPE_CHOICE, null=True, blank=True)
    file_name = models.TextField()
    
    def get_columns(self):
        if self.combo_type is None:
            return ([], []) 
        
        csv_results_qs = CSVResult.get_for_project(self.project)
        if self.combo_type == ComboType.REGION_STATS:
            columns_qs = csv_results_qs.filter(result_type=CSVResultType.REGION_STATS)
        else:
            result_types = [CSVResultType.GENE_SCORES]
            result_types.extend(CSVResultType.UPLOADED_CSVRESULTS)
            columns_qs = csv_results_qs.filter(result_type__in=result_types)
        
        selected_column_ids = self.combocolumn_set.all().values_list("csv_result_id", flat=True)
        selected_columns = CSVResult.objects.filter(id__in=selected_column_ids).order_by("combocolumn__sort_order")
        available_columns = columns_qs.exclude(id__in=selected_column_ids)
        return (available_columns, selected_columns)

    def get_dataframe(self):
        dataframes = []
        for cc in self.combocolumn_set.all().order_by("sort_order"):
            cc_df = cc.csv_result.get_dataframe()
            dataframes.append(cc_df)
            
        df = pd.concat(dataframes, axis=1)
        return df

    @staticmethod
    def get_csv_result_type_mappings():
        ''' Basically a way to have expression types map the same '''
        mappings = {k : k for (k,_) in CSVResultType.CHOICES}
        mappings[CSVResultType.SINGLE_SAMPLE_EXPRESSION] = 'Expression'
        mappings[CSVResultType.MULTI_SAMPLE_EXPRESSION] = 'Expression'
        return mappings

    def get_column_types_and_homogeneity(self):
        ''' returns (num_column_types, distinct_column_types, is_homogenous) '''

        mappings = self.get_csv_result_type_mappings()
        column_types = list(self.combocolumn_set.all().values_list('csv_result__result_type', flat=True))

        num_column_types = len(column_types)
        distinct_column_types = set(mappings[t] for t in column_types) 
        is_homogenous = len(distinct_column_types) <= 1

        return (num_column_types, distinct_column_types, is_homogenous)
        
    def is_multi_expression(self):
        (num_column_types, distinct_column_types, is_homogenous) = self.get_column_types_and_homogeneity()
        return num_column_types > 1 and is_homogenous and "Expression" in distinct_column_types

    
    def __unicode__(self):
        return "Combo: %s%s" % (self.name or '', self.project)

class GenomicAnchor(object):
    TSS = 'P'
    GENE_START_END = 'G'
    GENOMIC_ANCHOR_CHOICE = (
        (TSS, 'TSS'),
        (GENE_START_END, 'Gene Start/End')
    )

class GenomicRange(models.Model):
    project = models.ForeignKey(Project)
    name = models.TextField()
    anchor = models.CharField(max_length=1, choices=GenomicAnchor.GENOMIC_ANCHOR_CHOICE)
    upstream = models.IntegerField()
    downstream = models.IntegerField()
    max_size = models.IntegerField()
    step_size = models.IntegerField()


def get_processing_dir(project_id):
    processing_dir = os.path.join(settings.PROCESSOR_OUTPUT_DIR, str(project_id))
    mk_path(processing_dir)
    posix_stat = os.stat(processing_dir)

    if settings.GROUP_NAME:
        try:
            uid = posix_stat.st_uid
            gid = grp.getgrnam(settings.GROUP_NAME).gr_gid
    #        print "Changing permissions:"
            os.chown(processing_dir, uid, gid)
    #        print "Changing group ownership:"
            os.chmod(processing_dir, posix_stat.st_mode | stat.S_IWGRP)
        except Exception as e:
            print e # Ignore
#    posix_stat = os.stat(processing_dir)
#    mode = posix_stat.st_mode
    
#    print "%s mode: %d" % (processing_dir, mode)
#    if not stat.S_IWGRP & mode:
#        print "Not writable by GROUP" 
#    if not stat.S_IWOTH & mode:
#        print "Not writable by others" 
    
    return processing_dir



class UploadedFile(models.Model):
    project = models.ForeignKey(Project)
    name = models.TextField()
    uploaded_file = models.FileField(upload_to='uploads', max_length=256)
    file_type = models.CharField(max_length=1, choices=UploadedFileTypes.UPLOADED_FILES_CHOICE)
    date = models.DateTimeField()
    def get_file(self):
        ''' returns the actual file on the server '''
        return self.uploaded_file.file.file

    def uses_reference(self):
        return UploadedFileTypes.requires_reference(self.file_type)

    def needs_reference_set(self):
        return self.uses_reference() and self.project.build is None

    def __unicode__(self):
        return "%s (%s)" % (self.name, self.get_file_type_display())

class ProcessingStatus(object):
    CREATED = 'C'
    PROCESSING = 'P'
    ERROR = 'E'
    SUCCESS = 'S'
    STATUS_CHOICE = (
        (CREATED, 'Created'),
        (PROCESSING, 'Processing'),
        (ERROR, 'Error'),
        (SUCCESS, 'Success'),
    )
    INCOMPLETE = (CREATED, PROCESSING)


class FileProcessingTask(models.Model):
    ''' This represents the celery execution of a Processor '''
    objects = InheritanceManager()
    project = models.ForeignKey(Project, null=True)
    name = models.TextField()
    status = models.CharField(max_length=1, choices=ProcessingStatus.STATUS_CHOICE)
    error_message = models.TextField()
    created_date = models.DateTimeField()
    start_date = models.DateTimeField(null=True)
    end_date = models.DateTimeField(null=True)
    items_processed = models.IntegerField(default=0)
    celery_task = models.CharField(max_length=36, null=True)

    @property
    def processing_seconds(self):
        if self.start_date and self.end_date:
            seconds = (self.end_date - self.start_date).total_seconds()
        else:
            seconds = None
        return seconds
    
    def get_base_name(self):
        ''' Used for any produced files '''
        return NotImplementedError()
    
    def uses_reference(self):
        return False
    
    def get_reference(self):
        return self.project.build.get_igenomes_reference()
    
    def get_results(self):
        return self.processingresult_set.select_subclasses().order_by('-id')


class UploadedFileProcessingTask(FileProcessingTask):
    uploaded_file = models.ForeignKey(UploadedFile)

    def get_base_name(self):

bgs/templates/bgs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}BioGraphServ{% endblock %}</title>
	<script type="text/javascript" src="/static/js/lib/jquery-3.1.1.min.js"></script>
	<script type="text/javascript" src="/static/js/lib/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/js/lib/jquery.form.js"></script>
	<script type="text/javascript" src="/static/js/lib/jquery.xcolor.min.js"></script>
	<script type="text/javascript" src="/static/js/lib/jquery.colorPicker.min.js"></script>
	<script type="text/javascript" src="/static/js/lib/prettyPhoto_compressed_3.1.5/js/jquery.prettyPhoto.js"></script>
	<script type="text/javascript" src="/static/js/lib/plotly-1.20.5.min.js"></script>

	<link rel="shortcut icon" type="image/x-icon" href="/static/images/favicon.ico" />
	<link href="/static/js/lib/jquery-ui-1.12.1.custom/jquery-ui.min.css" rel="stylesheet">
	<link href="/static/css/colorPicker.css"" rel="stylesheet"></link>
	<link rel="stylesheet" href="/static/js/lib/prettyPhoto_compressed_3.1.5/css/prettyPhoto.css" type="text/css" media="screen" title="prettyPhoto main stylesheet" charset="utf-8" />
	<link href="/static/css/menu-top.css" rel="stylesheet">
	<link href="/static/css/biographserv.css" rel="stylesheet">

	<style type="text/css">
	html, body {
		font-family: Helvetica, Arial, Sans-Serif;		
		width:		100%;
		height:		100%;
		padding:	0;
		margin:		0;
	}

	div#content {
		width:		100%;
		height:		100%;					
		padding:	0;
		margin:		0;
		overflow: auto;
		flex-grow: 1;
	}

	.flex-container {
		display: -webkit-box;
		display: -moz-box;
		display: -ms-flexbox;
		display: -webkit-flex;
		display: flex;
		-webkit-flex-flow: row wrap;
		flex-flow: row wrap;
	}
	
	#siteMenuBar {
		height: 30px;
		width: 100%;
	}

	{% block css %}{% endblock %}
	</style>

	<script type="text/javascript">
		{% block jshead %}{% endblock %}
		$(document).ready(function () {
		    {% block jsdocumentready %}{% endblock %}
		});
	</script>

	<!-- head block -->
    {% block head %}{% endblock %}
	<!-- /head block -->
</head>

<body>
<div class='flex-container'>
	<div id="siteMenuBar">
		<div id="menuContainer" class="ui-widget-header">
			<ul>
				<li><a href="/"><div class='biographserv-logo'></div></a></li>
				<li><a href="{% url 'docs' 'doc_index' %}">Docs</a></li>
				<li><a href="{% url 'view_project' 'sample_project' %}">Sample Data</a></li>
			</ul>
		</div>
	</div>
    <div id="content" class='flex-container'>
        {% block content %}{% endblock %}
    </div>
</div>
</body>
</html>

bgs/templates/bgs/base_task_poller.html
<!-- head block -->
{% block head %}{% endblock %}
<!-- /head block -->
<script>
	if (window.task_update_timeout) {
		window.clearTimeout(window.task_update_timeout);
		window.task_update_timeout = null;
	}

	var UPDATE_FREQUENCY = 2000;
	var incomplete_tasks = {
	{% for task in incomplete_tasks %}
		{{ task.id }} : true,
	{% endfor %}
	};

	var failed_tasks = {
		{% for task in failed_tasks %}
			{{ task.id }} : { name : "{{ task.name }}", error_message: "{{ task.error_message }}" },
		{% endfor %}
	};

	var task_results = {};

	function tasks_status_callback(callback_data) {
		//console.log(callback_data);
		$.each(callback_data, function (taskId, data) {
			var status = data['status'];
			if (status == 'E') {
				delete incomplete_tasks[taskId];
				failed_tasks[taskId] = data;
			} else if (status == 'S') {
				delete incomplete_tasks[taskId];
				task_results[taskId] = data;
			}
		});

		tasks_display();
		window.task_update_timeout = window.setTimeout(tasks_update, UPDATE_FREQUENCY);
	}

	function add_task_results() {
		{% block add_task_results %}{% endblock %}
	}

	function all_tasks_complete() {
		$("#incomplete-tasks").remove();
		{% block all_tasks_complete %}{% endblock %}
	}

	function tasks_display() {
		var num_failed_tasks = Object.keys(failed_tasks);
		if (num_failed_tasks.length) {
			$('#failed-tasks').show();

			$.each(failed_tasks, function (taskId, data) {
				var error_message = data['error_message'] || '';
				var liElement = $("<li>" + data['name'] + ": " + error_message + "</li>");
				liElement.hide();
				$("#failed-task-list").append(liElement);
				liElement.fadeIn();
			});
			failed_tasks = {};
		}

		add_task_results();
		task_results = {};
	
		var tasks = Object.keys(incomplete_tasks);
		if (tasks.length) {
			$('#waiting-message').html("Waiting on " + tasks.length + " tasks.");
		} else {
			all_tasks_complete();
		}
	}

	function tasks_update() {
		// Make sure that div is still there so we don't keep polling after moving away from page
		if ($("#incomplete-tasks").length) {
			var tasks = Object.keys(incomplete_tasks);
			var data = 'csrfmiddlewaretoken={{ csrf_token }}&tasks=' + encodeURIComponent(JSON.stringify(tasks));
			$.ajax({
			    type: "POST",
			    data: data,
			    url: "{% url 'poll_task_results' project.pk %}",
			    success: tasks_status_callback,
			});
		}
	}

	{% block jshead %}{% endblock %}

	$(document).ready(function() {
		tasks_display();
		tasks_update();

	    {% block jsdocumentready %}{% endblock %}
	});
</script>



<div>
	{% block content_above_tasks %}{% endblock %}

	<div id='failed-tasks' style='display: none'>
		<b>The following errors occured:</b>
		<ul id='failed-task-list'>
		</ul>		
	</div>

	{% if incomplete_tasks %}
		<div id='incomplete-tasks'>
		<span id='waiting-message'></span>
		</div>
	{% endif %}

	{% block content_below_tasks %}{% endblock %}

</div>

bgs/templates/bgs/combo_graphs.html
{% extends "bgs/view_uploaded_file.html" %}

{% block content_above_tasks %}
{# Empty on purpose #}
{% endblock %}

bgs/templates/bgs/view_combo.html
<style>
.connectedSortable {
	min-height: 50px;
}

#columns-widget ul
{
	list-style-type: none;
}

#columns-widget li
{
	display: inline-block;
	margin: 0;
	padding: 0 5px 0 5px;
	margin-right: 10px;
	border: 1px solid #eee;
}

</style>

<script>
	function save_combo_columns() {
		var csv_result_ids = [];
		$("li", "ul#selected_columns_sortable").each(function() {
			csv_result_ids.push($(this).attr("csv_result_id"));
		});
		
		var data = 'csrfmiddlewaretoken={{ csrf_token }}&csv_result_ids=' + encodeURIComponent(JSON.stringify(csv_result_ids));
		console.log(data);
		$.ajax({
		    type: "POST",
		    data: data,
		    url: "{% url 'save_combo_columns' project.pk combo.pk %}",
		    success: function() {
				$("#unsaved-columns-message").hide();
				$("#columns-save-message").fadeIn(function() { $(this).fadeOut(1500); });
		    },
		});
	}


	$(document).ready(function() {
		$("button.save-button").button({
			icons: {primary: "ui-icon-disk"},
	    });

		var options	= {
			target: '#view-combo',
			success: function() {
				if ($(".errorlist", "form#project-form").length == 0) { // success
					$("#save-message").fadeIn(function() { $(this).fadeOut(1500); });

					var name = $("#id_name", "#combo-form").val();
					var combo = get_combo_row( {{ combo.pk }} );
					$("a", combo).text(name)
				}
			},
		};
			
		$('form#combo-form').ajaxForm(options); 

		///
		$(".connectedSortable").sortable({
		    items: "li.user_column",
		    placeholder: "sort_placeholder",
		    connectWith: '.connectedSortable',
		}).disableSelection();

		$("#selected_columns_sortable").bind("sortupdate", function(event, ui) {
			$("#unsaved-columns-message").fadeIn();
			console.log("Updated!");
		});
		
		$('#save-columns').click(save_combo_columns);
		
		$('#combo-tabs').tabs();
		
	});
</script>
<div id='view-combo'>
	<form id='combo-form' method="post" action="{{ request.path }}">
        {% csrf_token %}
		<table>
			{% for field in form %}
			<tr>
				<td>
				{% if field.field.required %}
				<span class="label"><span class="required">{{ field.label }}</span></span>
		        {% else %}
		        <span class="label">{{ field.label }}</span>
		        {% endif %}
				<td>{{ field.errors }}
					{{ field }}
			</tr>
			{% endfor %}
			<tr>
				<td>
				<button id='save-combo' class='save-button'>save</button>
				<td>
				<span id='save-message' style='display: none'>Saved Successfully</span>
			</tr>
		</table>
	</form>

	<div>
	{% if combo.combo_type %}
		<div id="combo-tabs"> 
		    <ul> 
		        <li><a href="{% url 'combo_columns' project.pk combo.pk %}">Columns</a></li> 
		        <li><a href="{% url 'combo_grid' project.pk combo.pk %}">Grid</a></li> 
		        <li><a href="{% url 'combo_graphs' project.pk combo.pk %}">Graphs</a></li> 
		    </ul>
		</div>​​​​​​​​​​
	{% else %}
		Please select a combo type		
	{% endif %}

	</div>

</div>

bgs/templates/bgs/view_uploaded_file.html
{% extends "bgs/base_task_poller.html" %}

{% block add_task_results %}
		$.each(task_results, function (taskId, data) {
			var base_url = "{% url 'task_results' project.pk 9999999999 %}";
			var url = base_url.replace(9999999999, taskId);

			var resultDiv = $("<div id='result'></div>");
			resultDiv.hide();
			$("#results").prepend(resultDiv);
			resultDiv.load(url, function() {
				initialiseResult(resultDiv);
				resultDiv.fadeIn()
			});
		});
		task_results = {};
{% endblock %}

{% block jshead %}
	function initialiseStyleToolkit(ppSelector) {
		var imageSelector = $(".generated-image", ppSelector);
		var styled_graph_id = imageSelector.attr("styled_graph_id");
		var styled_graph_hash_code = $(imageSelector).attr("styled_graph_hash_code");

		var base_url = "{% url 'styled_graph_editor' project.pk 9999999999 'HASH_CODE_PLACEHOLDER' %}";
		var url = base_url.replace(9999999999, styled_graph_id);
		url = url.replace('HASH_CODE_PLACEHOLDER', styled_graph_hash_code);

		var editorContainer = $(".styled-graph-editor-container", ppSelector);
		var imageContainer = $(".toolkit-image-container", ppSelector);

		var parent_h = ppSelector.parent().height();
		var PADDING = 0;
		ppSelector.height(parent_h - PADDING);
		editorContainer.load(url);
	}

	function initialiseResult(resultsSelector) {
		$(".image-container", resultsSelector).hover(
			function() {
				$(".overlay-background", this).stop().animate({"opacity": "0.6"}, 350);
				$(".overlay-buttons", this).stop().animate({"opacity": "1"}, 350);
			},
			function() {
				$(".overlay-background", this).stop().animate({"opacity": "0"}, 350);
				$(".overlay-buttons", this).stop().animate({"opacity": "0"}, 350);
		});

		var buttons_selector = $(".download-image-button", resultsSelector);
		buttons_selector.button({
	      icons: {
	        primary: "ui-icon-arrowthickstop-1-s"
	      }
	    });

		$("a[rel^='prettyPhoto']", resultsSelector).prettyPhoto({
			inline_markup: '<div class="my_pp_inline">{content}</div>',
			social_tools: false,
			changepicturecallback: function(){
				var ppSelector = $(".my_pp_inline");
				initialiseStyleToolkit(ppSelector);
			},
		});
	}
	
	function changeUploadedName() {
		if ($(".errorlist", "form#name-form").length == 0) { // success
			$("#save-message").fadeIn(function() { $(this).fadeOut(1500); });
	
			var name = $("#id_name", "#name-form").val();
			get_uploaded_file_link({{ uploaded_file.pk }}).text(name);
		}
	}

    function loadGraph(divId, data, layout) {
        Plotly.newPlot(divId, data, layout);
    }

	
{% endblock %}


{% block jsdocumentready %}
	initialiseResult($("#results")); // do for all

	var options	= {
		target: '#view-uploaded-file',
		complete: changeUploadedName, // success isn't being called (not sure why) - we check for errors in this function
	};
		
	$('form#name-form').ajaxForm(options); 

	$("button#save-uploaded-file").button({
		icons: {primary: "ui-icon-disk"},
    });

{% if data_sources %}
    var dataSources = {{ data_sources | safe }};
{% endif %}


{% if graphs_to_load %}
    var graphsToLoad = {{ graphs_to_load | safe }};
    for (var i=0 ; i<graphsToLoad.length; ++i) {
        var graph_data = graphsToLoad[i];
        var divId = "result-graph-" + graph_data[0];
        var data = dataSources[graph_data[1]];
        var layout = graph_data[2];
        console.log("layout:");
        console.log(layout);
        loadGraph(divId, data, layout);
    }

{% endif %}


{% endblock %}

{% block content_above_tasks %}
	<form id='name-form' method="post" action="{{ request.path }}">
        {% csrf_token %}
	<h3>Uploaded File: {{ name_form.name }}<button id='save-uploaded-file'>save</button> </h3> 
	<span id='save-message' style='display: none'>Saved Successfully</span>
	</form>
{% endblock %}

{% block content_below_tasks %}
	<div id='results'>
		{% include 'bgs/results.html' %}
	</div>
{% endblock %}
	    